import type { Locale } from '@/lib/types';

export const languages: Array<{ value: Locale; label: string; dir: 'ltr' | 'rtl' }> = [
  { value: 'en', label: 'English', dir: 'ltr' },
  { value: 'zh', label: '中文', dir: 'ltr' },
  { value: 'hi', label: 'हिन्दी', dir: 'ltr' },
  { value: 'es', label: 'Español', dir: 'ltr' },
  { value: 'ar', label: 'العربية', dir: 'rtl' },
  { value: 'fr', label: 'Français', dir: 'ltr' },
  { value: 'bn', label: 'বাংলা', dir: 'ltr' },
  { value: 'pt', label: 'Português', dir: 'ltr' },
  { value: 'ru', label: 'Русский', dir: 'ltr' },
  { value: 'tr', label: 'Türkçe', dir: 'ltr' },
];

const en = {
  'nav.notes': 'Notes', 'nav.reminders': 'Reminders', 'nav.calendar': 'Calendar', 'nav.shared': 'Shared', 'nav.colors': 'Colors', 'nav.labels': 'Labels', 'nav.archive': 'Archive', 'nav.trash': 'Trash', 'nav.settings': 'Settings', 'nav.createLabel': 'Create label',
  'search': 'Search notes', 'newNote': 'Take a note…', 'newChecklist': 'New checklist', 'pinned': 'PINNED', 'others': 'OTHERS',
  'empty.noMatch': 'No matching notes', 'empty.trash': 'Trash is empty', 'empty.archive': 'Archive is empty', 'empty.first': 'Create your first note', 'empty.searchHint': 'Try another search term.', 'empty.trashHint': 'Deleted notes appear here.', 'empty.firstHint': 'Leave it in Suur before the thought disappears.',
  'untitled': 'Untitled note', 'blankItem': 'Empty item', 'moreItems': '+{count} items', 'restore': 'Restore', 'deleteForever': 'Delete forever', 'pin': 'Pin', 'unpin': 'Unpin', 'archive': 'Archive', 'unarchive': 'Unarchive', 'moveTrash': 'Move to trash',
  'readMode': 'READ MODE', 'trashMode': 'TRASH', 'edit': 'Edit', 'close': 'Close', 'save': 'Save', 'emptyText': 'This note has no text.',
  'editor.new': 'NEW NOTE', 'editor.edit': 'EDIT NOTE', 'editor.title': 'Title', 'editor.item': 'List item', 'editor.addItem': 'Add item', 'editor.reminder': 'Reminder', 'editor.labels': 'Labels', 'editor.noLabels': 'No labels yet.', 'editor.text': 'Text note', 'editor.checklist': 'Checklist', 'editor.attachment': 'Add attachment', 'editor.assignee': 'Assigned user', 'editor.color': 'Note color', 'editor.voice': 'Voice note', 'editor.preview': 'Preview', 'editor.more': 'More options',
  'labels.edit': 'EDIT', 'labels.new': 'New label', 'labels.chooseColor': 'Choose label color', 'labels.delete': 'Delete label', 'labels.empty': 'Create your first label to organize notes.', 'labels.colorError': 'Label color could not be updated.',
  'color.default':'Default','color.mint':'Mint','color.sage':'Sage','color.sand':'Sand','color.rose':'Rose','color.sky':'Sky','color.lavender':'Lavender',
  'status.saved': 'Saved', 'status.saving': 'Saving…', 'status.offline': 'Offline', 'status.synced': 'Synced', 'status.syncing': 'Syncing',
  'sort.title': 'Sort notes', 'sort.manual': 'Custom order', 'sort.updated-desc': 'Recently updated', 'sort.updated-asc': 'Least recently updated', 'sort.created-desc': 'Newest created', 'sort.created-asc': 'Oldest created', 'sort.title-asc': 'Title A–Z',
  'filter.title': 'Filter notes', 'filter.active': '{count} active filters', 'filter.hint': 'Narrow the results', 'filter.color': 'Color', 'filter.label': 'Label', 'filter.allLabels': 'All labels', 'filter.updated': 'Updated', 'filter.anyTime': 'Any time', 'filter.today': 'Last 24 hours', 'filter.week': 'Last 7 days', 'filter.month': 'Last 30 days', 'filter.reminder': 'Reminder', 'filter.all': 'All', 'filter.withReminder': 'With reminder', 'filter.withoutReminder': 'Without reminder', 'filter.clear': 'Clear all filters',
  'settings.language': 'Language', 'settings.languageHelp': 'Interface and date format', 'settings.appearance': 'Appearance', 'settings.profile': 'Profile', 'settings.users': 'Users', 'settings.data': 'Data & backup', 'settings.labels': 'Labels', 'settings.signOut': 'Sign out', 'settings.advanced': 'Advanced', 'settings.about': 'About',
  'about.attribution': 'Designed and coded by H. N. Güleroğlu out of boredom.', 'about.contact': 'Contact', 'about.original': 'Original application identity', 'about.version': 'Version', 'about.source': 'Source code', 'about.license': 'License', 'about.storage': 'Storage', 'about.storageValue': 'Your server · SQLite',
  'login.eyebrow': 'YOUR SPACE, YOUR NOTES', 'login.hero': 'Keep your thoughts\nwhere they belong.', 'login.heroText': 'Fast notes, a calm interface, and a server that belongs to you.', 'login.welcome': 'WELCOME BACK', 'login.title': 'Return to your notes', 'login.description': 'Sign in with your Suur account to continue.', 'login.username': 'Username', 'login.password': 'Password', 'login.action': 'Sign in', 'login.loading': 'Signing in…', 'login.private': 'Secure, personal, and self-hosted.', 'login.invalid': 'The username or password is incorrect.', 'login.failed': 'Sign-in could not be completed.', 'login.showPassword': 'Show password', 'login.hidePassword': 'Hide password',
  'page.login': 'Sign in', 'share.readOnly': 'Read-only note', 'share.sharedNote': 'Shared note', 'share.lightMode': 'Use light mode', 'share.darkMode': 'Use dark mode',
} as const;

type MessageKey = keyof typeof en;
type Messages = Partial<Record<MessageKey, string>>;

const translations: Record<Locale, Messages> = {
  en,
  tr: {
    'nav.notes': 'Notlar', 'nav.reminders': 'Hatırlatıcılar', 'nav.calendar': 'Takvim', 'nav.labels': 'Etiketler', 'nav.archive': 'Arşiv', 'nav.trash': 'Çöp kutusu', 'nav.settings': 'Ayarlar', 'nav.createLabel': 'Etiket oluştur',
    'search': 'Notlarda ara', 'newNote': 'Bir not al…', 'newChecklist': 'Yeni checklist', 'pinned': 'SABİTLENMİŞ', 'others': 'DİĞER',
    'empty.noMatch': 'Eşleşen not bulunamadı', 'empty.trash': 'Çöp kutusu boş', 'empty.archive': 'Arşiv boş', 'empty.first': 'İlk notunu oluştur', 'empty.searchHint': 'Başka bir kelimeyle aramayı dene.', 'empty.trashHint': 'Sildiğin notlar burada görünür.', 'empty.firstHint': 'Aklındakini kaybetmeden Suur’a bırak.',
    'untitled': 'Başlıksız not', 'blankItem': 'Boş öğe', 'moreItems': '+{count} öğe', 'restore': 'Geri yükle', 'deleteForever': 'Kalıcı sil', 'pin': 'Sabitle', 'unpin': 'Sabitlemeyi kaldır', 'archive': 'Arşivle', 'unarchive': 'Arşivden çıkar', 'moveTrash': 'Çöp kutusuna taşı',
    'readMode': 'OKUMA MODU', 'trashMode': 'ÇÖP KUTUSU', 'edit': 'Düzenle', 'close': 'Kapat', 'save': 'Kaydet', 'emptyText': 'Bu notta metin yok.',
    'editor.new': 'YENİ NOT', 'editor.edit': 'NOTU DÜZENLE', 'editor.title': 'Başlık', 'editor.item': 'Liste öğesi', 'editor.addItem': 'Öğe ekle', 'editor.reminder': 'Hatırlatıcı', 'editor.labels': 'Etiketler', 'editor.noLabels': 'Henüz etiket yok.', 'editor.text': 'Metin notu', 'editor.checklist': 'Checklist', 'editor.attachment': 'Dosya ekle',
    'status.saved': 'Kaydedildi', 'status.saving': 'Kaydediliyor…', 'status.offline': 'Çevrimdışı', 'status.synced': 'Senkronize', 'status.syncing': 'Senkronize ediliyor',
    'settings.language': 'Dil', 'settings.languageHelp': 'Arayüz ve tarih biçimi', 'settings.appearance': 'Görünüm',
    'login.eyebrow': 'KENDİ ALANIN, KENDİ NOTLARIN', 'login.hero': 'Aklındakini\nyerinde tut.', 'login.heroText': 'Hızlı notlar, sakin bir arayüz ve yalnızca sana ait bir sunucu.', 'login.welcome': 'HOŞ GELDİN', 'login.title': 'Notlarına dön', 'login.description': 'Devam etmek için Suur hesabınla giriş yap.', 'login.username': 'Kullanıcı adı', 'login.password': 'Şifre', 'login.action': 'Giriş yap', 'login.loading': 'Giriş yapılıyor…', 'login.private': 'Güvenli, kişisel ve self-hosted.', 'login.invalid': 'Kullanıcı adı veya şifre hatalı.', 'login.failed': 'Giriş işlemi tamamlanamadı.', 'login.showPassword': 'Şifreyi göster', 'login.hidePassword': 'Şifreyi gizle',
    'page.login': 'Giriş', 'share.readOnly': 'Salt-okunur not', 'share.sharedNote': 'Paylaşılan not', 'share.lightMode': 'Açık modu kullan', 'share.darkMode': 'Karanlık modu kullan',
  },
  zh: {
    'page.login':'登录','share.readOnly':'只读笔记','share.sharedNote':'共享笔记','share.lightMode':'使用浅色模式','share.darkMode':'使用深色模式',
    'empty.searchHint':'请尝试其他搜索词。','empty.trashHint':'已删除的笔记会显示在这里。','empty.firstHint':'在想法消失前记录到 Suur。','moreItems':'+{count} 个项目','emptyText':'此笔记没有文字。',
    'editor.assignee':'分配的用户','editor.color':'笔记颜色','editor.voice':'语音笔记','editor.preview':'预览','editor.more':'更多选项','labels.edit':'编辑','labels.new':'新标签','labels.chooseColor':'选择标签颜色','labels.delete':'删除标签','labels.empty':'创建第一个标签来整理笔记。','labels.colorError':'无法更新标签颜色。','settings.appearance':'外观',
    'login.eyebrow':'你的空间，你的笔记','login.hero':'把想法留在\n属于它的地方。','login.heroText':'快速笔记、宁静界面，以及属于你的服务器。',
    'nav.notes':'笔记','nav.reminders':'提醒','nav.labels':'标签','nav.archive':'归档','nav.trash':'回收站','nav.settings':'设置','nav.createLabel':'新建标签','search':'搜索笔记','newNote':'记下内容…','newChecklist':'新建清单','pinned':'已置顶','others':'其他','empty.noMatch':'没有匹配的笔记','empty.trash':'回收站为空','empty.archive':'归档为空','empty.first':'创建第一条笔记','untitled':'无标题笔记','blankItem':'空项目','restore':'恢复','deleteForever':'永久删除','pin':'置顶','unpin':'取消置顶','archive':'归档','unarchive':'取消归档','moveTrash':'移至回收站','readMode':'阅读模式','trashMode':'回收站','edit':'编辑','close':'关闭','editor.new':'新笔记','editor.edit':'编辑笔记','editor.title':'标题','editor.item':'清单项目','editor.addItem':'添加项目','editor.reminder':'提醒','editor.labels':'标签','editor.noLabels':'暂无标签','editor.text':'文字笔记','editor.checklist':'清单','editor.attachment':'添加附件','status.saved':'已保存','status.saving':'保存中…','status.offline':'离线','status.synced':'已同步','status.syncing':'同步中','settings.language':'语言','settings.languageHelp':'界面和日期格式','login.welcome':'欢迎回来','login.title':'返回你的笔记','login.description':'请登录 Suur 账户以继续。','login.username':'用户名','login.password':'密码','login.action':'登录','login.loading':'正在登录…','login.private':'安全、私有、自托管。'
  },
  hi: {
    'page.login':'साइन इन','share.readOnly':'केवल पढ़ने योग्य नोट','share.sharedNote':'साझा नोट','share.lightMode':'हल्का मोड इस्तेमाल करें','share.darkMode':'गहरा मोड इस्तेमाल करें',
    'empty.noMatch':'कोई मेल खाता नोट नहीं','empty.trash':'कचरा खाली है','empty.archive':'संग्रह खाली है','empty.first':'अपना पहला नोट बनाएँ','empty.searchHint':'कोई दूसरा खोज शब्द आज़माएँ।','empty.trashHint':'मिटाए गए नोट यहाँ दिखाई देते हैं।','empty.firstHint':'विचार खोने से पहले उसे Suur में लिखें।','blankItem':'खाली आइटम','moreItems':'+{count} आइटम','trashMode':'कचरा','emptyText':'इस नोट में कोई टेक्स्ट नहीं है।','editor.noLabels':'अभी कोई लेबल नहीं।','editor.text':'टेक्स्ट नोट','editor.checklist':'चेकलिस्ट',
    'editor.assignee':'असाइन किया गया उपयोगकर्ता','editor.color':'नोट का रंग','editor.voice':'वॉइस नोट','editor.preview':'पूर्वावलोकन','editor.more':'अधिक विकल्प','labels.edit':'संपादित करें','labels.new':'नया लेबल','labels.chooseColor':'लेबल का रंग चुनें','labels.delete':'लेबल मिटाएँ','labels.empty':'नोट व्यवस्थित करने के लिए पहला लेबल बनाएँ।','labels.colorError':'लेबल का रंग अपडेट नहीं हुआ।','settings.appearance':'दिखावट',
    'login.eyebrow':'आपकी जगह, आपके नोट्स','login.hero':'अपने विचारों को\nसही जगह रखें।','login.heroText':'तेज़ नोट्स, शांत इंटरफ़ेस और आपका अपना सर्वर।',
    'nav.notes':'नोट्स','nav.reminders':'रिमाइंडर','nav.labels':'लेबल','nav.archive':'संग्रह','nav.trash':'कचरा','nav.settings':'सेटिंग्स','nav.createLabel':'लेबल बनाएँ','search':'नोट्स खोजें','newNote':'एक नोट लिखें…','newChecklist':'नई चेकलिस्ट','pinned':'पिन किए गए','others':'अन्य','untitled':'बिना शीर्षक का नोट','restore':'वापस लाएँ','deleteForever':'हमेशा के लिए मिटाएँ','pin':'पिन करें','unpin':'पिन हटाएँ','archive':'संग्रहित करें','unarchive':'संग्रह से हटाएँ','moveTrash':'कचरे में डालें','readMode':'पढ़ने का मोड','edit':'संपादित करें','close':'बंद करें','editor.new':'नया नोट','editor.edit':'नोट संपादित करें','editor.title':'शीर्षक','editor.item':'सूची आइटम','editor.addItem':'आइटम जोड़ें','editor.reminder':'रिमाइंडर','editor.labels':'लेबल','editor.attachment':'फ़ाइल जोड़ें','status.saved':'सहेजा गया','status.saving':'सहेज रहे हैं…','status.offline':'ऑफ़लाइन','settings.language':'भाषा','settings.languageHelp':'इंटरफ़ेस और तारीख प्रारूप','login.welcome':'वापसी पर स्वागत है','login.title':'अपने नोट्स पर लौटें','login.description':'जारी रखने के लिए अपने Suur खाते से साइन इन करें।','login.username':'उपयोगकर्ता नाम','login.password':'पासवर्ड','login.action':'साइन इन','login.loading':'साइन इन हो रहा है…','login.private':'सुरक्षित, निजी और स्वयं होस्टेड।'
  },
  es: {
    'page.login':'Iniciar sesión','share.readOnly':'Nota de solo lectura','share.sharedNote':'Nota compartida','share.lightMode':'Usar modo claro','share.darkMode':'Usar modo oscuro',
    'empty.searchHint':'Prueba con otro término de búsqueda.','empty.trashHint':'Las notas eliminadas aparecen aquí.','empty.firstHint':'Guárdalo en Suur antes de que la idea desaparezca.','moreItems':'+{count} elementos','emptyText':'Esta nota no tiene texto.',
    'editor.assignee':'Usuario asignado','editor.color':'Color de la nota','editor.voice':'Nota de voz','editor.preview':'Vista previa','editor.more':'Más opciones','labels.edit':'EDITAR','labels.new':'Nueva etiqueta','labels.chooseColor':'Elegir color de etiqueta','labels.delete':'Eliminar etiqueta','labels.empty':'Crea tu primera etiqueta para organizar notas.','labels.colorError':'No se pudo actualizar el color de la etiqueta.','settings.appearance':'Apariencia',
    'login.eyebrow':'TU ESPACIO, TUS NOTAS','login.hero':'Guarda tus ideas\ndonde corresponden.','login.heroText':'Notas rápidas, una interfaz tranquila y un servidor propio.',
    'nav.notes':'Notas','nav.reminders':'Recordatorios','nav.labels':'Etiquetas','nav.archive':'Archivo','nav.trash':'Papelera','nav.settings':'Ajustes','nav.createLabel':'Crear etiqueta','search':'Buscar notas','newNote':'Escribe una nota…','newChecklist':'Nueva lista','pinned':'FIJADAS','others':'OTRAS','empty.noMatch':'No hay notas coincidentes','empty.trash':'La papelera está vacía','empty.archive':'El archivo está vacío','empty.first':'Crea tu primera nota','untitled':'Nota sin título','blankItem':'Elemento vacío','restore':'Restaurar','deleteForever':'Eliminar para siempre','pin':'Fijar','unpin':'Desfijar','archive':'Archivar','unarchive':'Desarchivar','moveTrash':'Mover a la papelera','readMode':'MODO LECTURA','trashMode':'PAPELERA','edit':'Editar','close':'Cerrar','editor.new':'NUEVA NOTA','editor.edit':'EDITAR NOTA','editor.title':'Título','editor.item':'Elemento de lista','editor.addItem':'Añadir elemento','editor.reminder':'Recordatorio','editor.labels':'Etiquetas','editor.noLabels':'Aún no hay etiquetas.','editor.text':'Nota de texto','editor.checklist':'Lista','editor.attachment':'Añadir archivo','status.saved':'Guardado','status.saving':'Guardando…','status.offline':'Sin conexión','status.synced':'Sincronizado','status.syncing':'Sincronizando','settings.language':'Idioma','settings.languageHelp':'Interfaz y formato de fecha','login.welcome':'HOLA DE NUEVO','login.title':'Vuelve a tus notas','login.description':'Inicia sesión con tu cuenta Suur para continuar.','login.username':'Usuario','login.password':'Contraseña','login.action':'Iniciar sesión','login.loading':'Iniciando sesión…','login.private':'Seguro, personal y autohospedado.'
  },
  ar: {
    'page.login':'تسجيل الدخول','share.readOnly':'ملاحظة للقراءة فقط','share.sharedNote':'ملاحظة مشتركة','share.lightMode':'استخدام الوضع الفاتح','share.darkMode':'استخدام الوضع الداكن',
    'empty.trash':'سلة المحذوفات فارغة','empty.archive':'الأرشيف فارغ','empty.first':'أنشئ ملاحظتك الأولى','empty.searchHint':'جرّب عبارة بحث أخرى.','empty.trashHint':'تظهر الملاحظات المحذوفة هنا.','empty.firstHint':'دوّن الفكرة في Suur قبل أن تضيع.','blankItem':'عنصر فارغ','moreItems':'+{count} عناصر','trashMode':'سلة المحذوفات','emptyText':'لا تحتوي هذه الملاحظة على نص.','editor.noLabels':'لا توجد تصنيفات بعد.','editor.text':'ملاحظة نصية','editor.checklist':'قائمة تحقق',
    'editor.assignee':'المستخدم المعيّن','editor.color':'لون الملاحظة','editor.voice':'ملاحظة صوتية','editor.preview':'معاينة','editor.more':'خيارات إضافية','labels.edit':'تعديل','labels.new':'تصنيف جديد','labels.chooseColor':'اختر لون التصنيف','labels.delete':'حذف التصنيف','labels.empty':'أنشئ أول تصنيف لتنظيم الملاحظات.','labels.colorError':'تعذر تحديث لون التصنيف.','settings.appearance':'المظهر',
    'login.eyebrow':'مساحتك، ملاحظاتك','login.hero':'احتفظ بأفكارك\nفي مكانها الصحيح.','login.heroText':'ملاحظات سريعة وواجهة هادئة وخادم تملكه أنت.',
    'nav.notes':'الملاحظات','nav.reminders':'التذكيرات','nav.labels':'التصنيفات','nav.archive':'الأرشيف','nav.trash':'سلة المحذوفات','nav.settings':'الإعدادات','nav.createLabel':'إنشاء تصنيف','search':'البحث في الملاحظات','newNote':'اكتب ملاحظة…','newChecklist':'قائمة جديدة','pinned':'مثبتة','others':'أخرى','empty.noMatch':'لا توجد ملاحظات مطابقة','untitled':'ملاحظة بلا عنوان','restore':'استعادة','deleteForever':'حذف نهائي','pin':'تثبيت','unpin':'إلغاء التثبيت','archive':'أرشفة','unarchive':'إلغاء الأرشفة','moveTrash':'نقل إلى سلة المحذوفات','readMode':'وضع القراءة','edit':'تعديل','close':'إغلاق','editor.new':'ملاحظة جديدة','editor.edit':'تعديل الملاحظة','editor.title':'العنوان','editor.item':'عنصر القائمة','editor.addItem':'إضافة عنصر','editor.reminder':'تذكير','editor.labels':'التصنيفات','editor.attachment':'إضافة ملف','status.saved':'تم الحفظ','status.saving':'جارٍ الحفظ…','status.offline':'غير متصل','settings.language':'اللغة','settings.languageHelp':'الواجهة وتنسيق التاريخ','login.welcome':'مرحبًا بعودتك','login.title':'عد إلى ملاحظاتك','login.description':'سجّل الدخول إلى حساب Suur للمتابعة.','login.username':'اسم المستخدم','login.password':'كلمة المرور','login.action':'تسجيل الدخول','login.loading':'جارٍ تسجيل الدخول…','login.private':'آمن وشخصي ومستضاف ذاتيًا.'
  },
  fr: {
    'page.login':'Connexion','share.readOnly':'Note en lecture seule','share.sharedNote':'Note partagée','share.lightMode':'Utiliser le mode clair','share.darkMode':'Utiliser le mode sombre',
    'empty.noMatch':'Aucune note correspondante','empty.trash':'La corbeille est vide','empty.archive':'Les archives sont vides','empty.first':'Créez votre première note','empty.searchHint':'Essayez un autre terme de recherche.','empty.trashHint':'Les notes supprimées apparaissent ici.','empty.firstHint':'Confiez-la à Suur avant que l’idée ne disparaisse.','blankItem':'Élément vide','moreItems':'+{count} éléments','trashMode':'CORBEILLE','emptyText':'Cette note ne contient aucun texte.','editor.noLabels':'Aucun libellé pour le moment.','editor.text':'Note textuelle','editor.checklist':'Liste',
    'editor.assignee':'Utilisateur assigné','editor.color':'Couleur de la note','editor.voice':'Note vocale','editor.preview':'Aperçu','editor.more':'Plus d’options','labels.edit':'MODIFIER','labels.new':'Nouveau libellé','labels.chooseColor':'Choisir la couleur du libellé','labels.delete':'Supprimer le libellé','labels.empty':'Créez votre premier libellé pour organiser les notes.','labels.colorError':'La couleur du libellé n’a pas pu être mise à jour.','settings.appearance':'Apparence',
    'login.eyebrow':'VOTRE ESPACE, VOS NOTES','login.hero':'Gardez vos idées\nà leur place.','login.heroText':'Des notes rapides, une interface apaisée et votre propre serveur.',
    'nav.notes':'Notes','nav.reminders':'Rappels','nav.labels':'Libellés','nav.archive':'Archives','nav.trash':'Corbeille','nav.settings':'Paramètres','nav.createLabel':'Créer un libellé','search':'Rechercher des notes','newNote':'Écrire une note…','newChecklist':'Nouvelle liste','pinned':'ÉPINGLÉES','others':'AUTRES','untitled':'Note sans titre','restore':'Restaurer','deleteForever':'Supprimer définitivement','pin':'Épingler','unpin':'Désépingler','archive':'Archiver','unarchive':'Désarchiver','moveTrash':'Mettre à la corbeille','readMode':'MODE LECTURE','edit':'Modifier','close':'Fermer','editor.new':'NOUVELLE NOTE','editor.edit':'MODIFIER LA NOTE','editor.title':'Titre','editor.item':'Élément de liste','editor.addItem':'Ajouter un élément','editor.reminder':'Rappel','editor.labels':'Libellés','editor.attachment':'Ajouter un fichier','status.saved':'Enregistré','status.saving':'Enregistrement…','status.offline':'Hors connexion','settings.language':'Langue','settings.languageHelp':'Interface et format de date','login.welcome':'BON RETOUR','login.title':'Retrouvez vos notes','login.description':'Connectez-vous à votre compte Suur pour continuer.','login.username':'Nom d’utilisateur','login.password':'Mot de passe','login.action':'Se connecter','login.loading':'Connexion…','login.private':'Sécurisé, personnel et auto-hébergé.'
  },
  bn: {
    'page.login':'সাইন ইন','share.readOnly':'শুধু-পঠন নোট','share.sharedNote':'শেয়ার করা নোট','share.lightMode':'হালকা মোড ব্যবহার করুন','share.darkMode':'গাঢ় মোড ব্যবহার করুন',
    'empty.noMatch':'মিলে যাওয়া নোট নেই','empty.trash':'ট্র্যাশ খালি','empty.archive':'আর্কাইভ খালি','empty.first':'আপনার প্রথম নোট তৈরি করুন','empty.searchHint':'অন্য শব্দ দিয়ে খুঁজে দেখুন।','empty.trashHint':'মুছে ফেলা নোট এখানে দেখা যায়।','empty.firstHint':'ভাবনা হারানোর আগে Suur-এ লিখে রাখুন।','blankItem':'খালি আইটেম','moreItems':'+{count}টি আইটেম','trashMode':'ট্র্যাশ','emptyText':'এই নোটে কোনো লেখা নেই।','editor.noLabels':'এখনও কোনো লেবেল নেই।','editor.text':'টেক্সট নোট','editor.checklist':'চেকলিস্ট',
    'editor.assignee':'নির্ধারিত ব্যবহারকারী','editor.color':'নোটের রং','editor.voice':'ভয়েস নোট','editor.preview':'প্রিভিউ','editor.more':'আরও বিকল্প','labels.edit':'সম্পাদনা','labels.new':'নতুন লেবেল','labels.chooseColor':'লেবেলের রং বেছে নিন','labels.delete':'লেবেল মুছুন','labels.empty':'নোট সাজাতে প্রথম লেবেল তৈরি করুন।','labels.colorError':'লেবেলের রং আপডেট করা যায়নি।','settings.appearance':'চেহারা',
    'login.eyebrow':'আপনার জায়গা, আপনার নোট','login.hero':'আপনার ভাবনা\nসঠিক জায়গায় রাখুন।','login.heroText':'দ্রুত নোট, শান্ত ইন্টারফেস এবং আপনার নিজস্ব সার্ভার।',
    'nav.notes':'নোট','nav.reminders':'রিমাইন্ডার','nav.labels':'লেবেল','nav.archive':'আর্কাইভ','nav.trash':'ট্র্যাশ','nav.settings':'সেটিংস','nav.createLabel':'লেবেল তৈরি','search':'নোট খুঁজুন','newNote':'একটি নোট লিখুন…','newChecklist':'নতুন চেকলিস্ট','pinned':'পিন করা','others':'অন্যান্য','untitled':'শিরোনামহীন নোট','restore':'ফিরিয়ে আনুন','deleteForever':'স্থায়ীভাবে মুছুন','pin':'পিন করুন','unpin':'পিন সরান','archive':'আর্কাইভ করুন','unarchive':'আর্কাইভ থেকে সরান','moveTrash':'ট্র্যাশে নিন','readMode':'পড়ার মোড','edit':'সম্পাদনা','close':'বন্ধ','editor.new':'নতুন নোট','editor.edit':'নোট সম্পাদনা','editor.title':'শিরোনাম','editor.item':'তালিকার আইটেম','editor.addItem':'আইটেম যোগ করুন','editor.reminder':'রিমাইন্ডার','editor.labels':'লেবেল','editor.attachment':'ফাইল যোগ করুন','status.saved':'সংরক্ষিত','status.saving':'সংরক্ষণ হচ্ছে…','status.offline':'অফলাইন','settings.language':'ভাষা','settings.languageHelp':'ইন্টারফেস ও তারিখের ধরন','login.welcome':'আবার স্বাগতম','login.title':'আপনার নোটে ফিরুন','login.description':'চালিয়ে যেতে Suur অ্যাকাউন্টে সাইন ইন করুন।','login.username':'ব্যবহারকারীর নাম','login.password':'পাসওয়ার্ড','login.action':'সাইন ইন','login.loading':'সাইন ইন হচ্ছে…','login.private':'নিরাপদ, ব্যক্তিগত ও স্ব-হোস্টেড।'
  },
  pt: {
    'page.login':'Entrar','share.readOnly':'Nota somente leitura','share.sharedNote':'Nota compartilhada','share.lightMode':'Usar modo claro','share.darkMode':'Usar modo escuro',
    'empty.noMatch':'Nenhuma nota encontrada','empty.trash':'A lixeira está vazia','empty.archive':'O arquivo está vazio','empty.first':'Crie sua primeira nota','empty.searchHint':'Tente outro termo de pesquisa.','empty.trashHint':'As notas excluídas aparecem aqui.','empty.firstHint':'Guarde no Suur antes que a ideia desapareça.','blankItem':'Item vazio','moreItems':'+{count} itens','trashMode':'LIXEIRA','emptyText':'Esta nota não tem texto.','editor.noLabels':'Ainda não há marcadores.','editor.text':'Nota de texto','editor.checklist':'Lista',
    'editor.assignee':'Usuário atribuído','editor.color':'Cor da nota','editor.voice':'Nota de voz','editor.preview':'Pré-visualização','editor.more':'Mais opções','labels.edit':'EDITAR','labels.new':'Novo marcador','labels.chooseColor':'Escolher cor do marcador','labels.delete':'Excluir marcador','labels.empty':'Crie seu primeiro marcador para organizar notas.','labels.colorError':'Não foi possível atualizar a cor do marcador.','settings.appearance':'Aparência',
    'login.eyebrow':'SEU ESPAÇO, SUAS NOTAS','login.hero':'Mantenha suas ideias\nno lugar certo.','login.heroText':'Notas rápidas, uma interface tranquila e seu próprio servidor.',
    'nav.notes':'Notas','nav.reminders':'Lembretes','nav.labels':'Marcadores','nav.archive':'Arquivo','nav.trash':'Lixeira','nav.settings':'Configurações','nav.createLabel':'Criar marcador','search':'Pesquisar notas','newNote':'Escreva uma nota…','newChecklist':'Nova lista','pinned':'FIXADAS','others':'OUTRAS','untitled':'Nota sem título','restore':'Restaurar','deleteForever':'Excluir para sempre','pin':'Fixar','unpin':'Desafixar','archive':'Arquivar','unarchive':'Desarquivar','moveTrash':'Mover para lixeira','readMode':'MODO DE LEITURA','edit':'Editar','close':'Fechar','editor.new':'NOVA NOTA','editor.edit':'EDITAR NOTA','editor.title':'Título','editor.item':'Item da lista','editor.addItem':'Adicionar item','editor.reminder':'Lembrete','editor.labels':'Marcadores','editor.attachment':'Adicionar arquivo','status.saved':'Salvo','status.saving':'Salvando…','status.offline':'Offline','settings.language':'Idioma','settings.languageHelp':'Interface e formato de data','login.welcome':'BEM-VINDO DE VOLTA','login.title':'Volte às suas notas','login.description':'Entre com sua conta Suur para continuar.','login.username':'Usuário','login.password':'Senha','login.action':'Entrar','login.loading':'Entrando…','login.private':'Seguro, pessoal e auto-hospedado.'
  },
  ru: {
    'page.login':'Вход','share.readOnly':'Заметка только для чтения','share.sharedNote':'Общая заметка','share.lightMode':'Включить светлую тему','share.darkMode':'Включить тёмную тему',
    'empty.noMatch':'Подходящих заметок нет','empty.trash':'Корзина пуста','empty.archive':'Архив пуст','empty.first':'Создайте первую заметку','empty.searchHint':'Попробуйте другой поисковый запрос.','empty.trashHint':'Удалённые заметки появятся здесь.','empty.firstHint':'Запишите мысль в Suur, пока она не исчезла.','blankItem':'Пустой пункт','moreItems':'+{count} пунктов','trashMode':'КОРЗИНА','emptyText':'В этой заметке нет текста.','editor.noLabels':'Ярлыков пока нет.','editor.text':'Текстовая заметка','editor.checklist':'Список',
    'editor.assignee':'Назначенный пользователь','editor.color':'Цвет заметки','editor.voice':'Голосовая заметка','editor.preview':'Предпросмотр','editor.more':'Другие параметры','labels.edit':'ИЗМЕНИТЬ','labels.new':'Новый ярлык','labels.chooseColor':'Выбрать цвет ярлыка','labels.delete':'Удалить ярлык','labels.empty':'Создайте первый ярлык для организации заметок.','labels.colorError':'Не удалось обновить цвет ярлыка.','settings.appearance':'Оформление',
    'login.eyebrow':'ВАШЕ ПРОСТРАНСТВО, ВАШИ ЗАМЕТКИ','login.hero':'Храните мысли\nна своём месте.','login.heroText':'Быстрые заметки, спокойный интерфейс и ваш собственный сервер.',
    'nav.notes':'Заметки','nav.reminders':'Напоминания','nav.labels':'Ярлыки','nav.archive':'Архив','nav.trash':'Корзина','nav.settings':'Настройки','nav.createLabel':'Создать ярлык','search':'Поиск заметок','newNote':'Новая заметка…','newChecklist':'Новый список','pinned':'ЗАКРЕПЛЕННЫЕ','others':'ДРУГИЕ','untitled':'Заметка без названия','restore':'Восстановить','deleteForever':'Удалить навсегда','pin':'Закрепить','unpin':'Открепить','archive':'В архив','unarchive':'Вернуть из архива','moveTrash':'В корзину','readMode':'РЕЖИМ ЧТЕНИЯ','edit':'Изменить','close':'Закрыть','editor.new':'НОВАЯ ЗАМЕТКА','editor.edit':'ИЗМЕНИТЬ ЗАМЕТКУ','editor.title':'Заголовок','editor.item':'Пункт списка','editor.addItem':'Добавить пункт','editor.reminder':'Напоминание','editor.labels':'Ярлыки','editor.attachment':'Добавить файл','status.saved':'Сохранено','status.saving':'Сохранение…','status.offline':'Нет сети','settings.language':'Язык','settings.languageHelp':'Интерфейс и формат даты','login.welcome':'С ВОЗВРАЩЕНИЕМ','login.title':'Вернитесь к заметкам','login.description':'Войдите в аккаунт Suur, чтобы продолжить.','login.username':'Имя пользователя','login.password':'Пароль','login.action':'Войти','login.loading':'Вход…','login.private':'Безопасно, лично и на своём сервере.'
  },
};

// Keep the most visible navigation and authentication feedback complete in
// every supported language, even while less common copy falls back to English.
const localeOverrides: Record<Locale, Messages> = {
  en: {},
  tr: { 'nav.shared': 'Paylaşılanlar', 'nav.colors': 'Renkler', 'sort.title':'Notları sırala','sort.manual':'Özel sıralama','sort.updated-desc':'Son düzenlenenler','sort.updated-asc':'En eski düzenlenenler','sort.created-desc':'En yeni oluşturulanlar','sort.created-asc':'En eski oluşturulanlar','sort.title-asc':'Başlığa göre A–Z','filter.title':'Notları filtrele','filter.active':'{count} filtre etkin','filter.hint':'Sonuçları daralt','filter.color':'Renk','filter.label':'Etiket','filter.allLabels':'Tüm etiketler','filter.updated':'Değiştirilme tarihi','filter.anyTime':'Her zaman','filter.today':'Son 24 saat','filter.week':'Son 7 gün','filter.month':'Son 30 gün','filter.reminder':'Hatırlatıcı','filter.all':'Tümü','filter.withReminder':'Olanlar','filter.withoutReminder':'Olmayanlar','filter.clear':'Tüm filtreleri temizle','settings.profile':'Profil','settings.users':'Kullanıcılar','settings.data':'Veri ve yedek','settings.labels':'Etiketler','settings.signOut':'Çıkış yap', 'settings.advanced': 'Gelişmiş', 'settings.about': 'Hakkında', 'about.attribution': 'H. N. Güleroğlu tarafından can sıkıntısından tasarlandı ve kodlandı.', 'about.contact': 'İletişim', 'about.original': 'Orijinal uygulama kimliği','about.version':'Sürüm','about.source':'Kaynak kodu','about.license':'Lisans','about.storage':'Depolama','about.storageValue':'Kendi sunucun · SQLite' },
  zh: { 'nav.calendar': '日历', 'nav.shared': '共享', 'nav.colors': '颜色', 'settings.advanced': '高级', 'settings.about': '关于', 'about.attribution': '由 H. N. Güleroğlu 出于无聊而设计和编码。', 'about.contact': '联系', 'about.original': '原始应用身份', 'save': '保存', 'status.synced': '已同步', 'status.syncing': '同步中', 'login.invalid': '用户名或密码不正确。', 'login.failed': '无法完成登录。', 'login.showPassword': '显示密码', 'login.hidePassword': '隐藏密码' },
  hi: { 'nav.calendar': 'कैलेंडर', 'nav.shared': 'साझा', 'nav.colors': 'रंग', 'settings.advanced': 'उन्नत', 'settings.about': 'परिचय', 'about.attribution': 'H. N. Güleroğlu द्वारा बोरियत में डिज़ाइन और कोड किया गया।', 'about.contact': 'संपर्क', 'about.original': 'मूल ऐप पहचान', 'save': 'सहेजें', 'status.synced': 'सिंक हुआ', 'status.syncing': 'सिंक हो रहा है', 'login.invalid': 'उपयोगकर्ता नाम या पासवर्ड गलत है।', 'login.failed': 'साइन इन पूरा नहीं हो सका।', 'login.showPassword': 'पासवर्ड दिखाएँ', 'login.hidePassword': 'पासवर्ड छिपाएँ' },
  es: { 'nav.calendar': 'Calendario', 'nav.shared': 'Compartidas', 'nav.colors': 'Colores', 'settings.advanced': 'Avanzado', 'settings.about': 'Acerca de', 'about.attribution': 'Diseñado y programado por H. N. Güleroğlu por puro aburrimiento.', 'about.contact': 'Contacto', 'about.original': 'Identidad original de la aplicación', 'save': 'Guardar', 'status.synced': 'Sincronizado', 'status.syncing': 'Sincronizando', 'login.invalid': 'El usuario o la contraseña son incorrectos.', 'login.failed': 'No se pudo iniciar sesión.', 'login.showPassword': 'Mostrar contraseña', 'login.hidePassword': 'Ocultar contraseña' },
  ar: { 'nav.calendar': 'التقويم', 'nav.shared': 'المشتركة', 'nav.colors': 'الألوان', 'settings.advanced': 'متقدم', 'settings.about': 'حول', 'about.attribution': 'صُمّم وبُرمج بواسطة H. N. Güleroğlu بدافع الملل.', 'about.contact': 'اتصال', 'about.original': 'هوية التطبيق الأصلية', 'save': 'حفظ', 'status.synced': 'تمت المزامنة', 'status.syncing': 'جارٍ المزامنة', 'login.invalid': 'اسم المستخدم أو كلمة المرور غير صحيحة.', 'login.failed': 'تعذر إكمال تسجيل الدخول.', 'login.showPassword': 'إظهار كلمة المرور', 'login.hidePassword': 'إخفاء كلمة المرور' },
  fr: { 'nav.calendar': 'Calendrier', 'nav.shared': 'Partagées', 'nav.colors': 'Couleurs', 'settings.advanced': 'Avancé', 'settings.about': 'À propos', 'about.attribution': 'Conçu et codé par H. N. Güleroğlu par ennui.', 'about.contact': 'Contact', 'about.original': 'Identité originale de l’application', 'save': 'Enregistrer', 'status.synced': 'Synchronisé', 'status.syncing': 'Synchronisation', 'login.invalid': 'Le nom d’utilisateur ou le mot de passe est incorrect.', 'login.failed': 'La connexion n’a pas pu être effectuée.', 'login.showPassword': 'Afficher le mot de passe', 'login.hidePassword': 'Masquer le mot de passe' },
  bn: { 'nav.calendar': 'ক্যালেন্ডার', 'nav.shared': 'শেয়ার করা', 'nav.colors': 'রং', 'settings.advanced': 'উন্নত', 'settings.about': 'সম্পর্কে', 'about.attribution': 'একঘেয়েমি থেকে H. N. Güleroğlu কর্তৃক ডিজাইন ও কোড করা হয়েছে।', 'about.contact': 'যোগাযোগ', 'about.original': 'মূল অ্যাপ পরিচয়', 'save': 'সংরক্ষণ করুন', 'status.synced': 'সিঙ্ক হয়েছে', 'status.syncing': 'সিঙ্ক হচ্ছে', 'login.invalid': 'ব্যবহারকারীর নাম বা পাসওয়ার্ড ভুল।', 'login.failed': 'সাইন ইন সম্পন্ন করা যায়নি।', 'login.showPassword': 'পাসওয়ার্ড দেখান', 'login.hidePassword': 'পাসওয়ার্ড লুকান' },
  pt: { 'nav.calendar': 'Calendário', 'nav.shared': 'Compartilhadas', 'nav.colors': 'Cores', 'settings.advanced': 'Avançado', 'settings.about': 'Sobre', 'about.attribution': 'Projetado e programado por H. N. Güleroğlu por puro tédio.', 'about.contact': 'Contato', 'about.original': 'Identidade original do aplicativo', 'save': 'Salvar', 'status.synced': 'Sincronizado', 'status.syncing': 'Sincronizando', 'login.invalid': 'O usuário ou a senha estão incorretos.', 'login.failed': 'Não foi possível entrar.', 'login.showPassword': 'Mostrar senha', 'login.hidePassword': 'Ocultar senha' },
  ru: { 'nav.calendar': 'Календарь', 'nav.shared': 'Общие', 'nav.colors': 'Цвета', 'settings.advanced': 'Расширенные', 'settings.about': 'О приложении', 'about.attribution': 'Разработано и запрограммировано H. N. Güleroğlu от скуки.', 'about.contact': 'Связь', 'about.original': 'Исходная идентичность приложения', 'save': 'Сохранить', 'status.synced': 'Синхронизировано', 'status.syncing': 'Синхронизация', 'login.invalid': 'Неверное имя пользователя или пароль.', 'login.failed': 'Не удалось выполнить вход.', 'login.showPassword': 'Показать пароль', 'login.hidePassword': 'Скрыть пароль' },
};

const featureTranslations: Record<Locale, Messages> = {
  en: {},
  tr: { 'editor.assignee':'Atanan kullanıcı','editor.color':'Not rengi','editor.voice':'Sesli not','editor.preview':'Önizleme','editor.more':'Diğer seçenekler','labels.edit':'DÜZENLE','labels.new':'Yeni etiket','labels.chooseColor':'Etiket rengi seç','labels.delete':'Etiketi sil','labels.empty':'Notlarını gruplamak için ilk etiketini oluştur.','labels.colorError':'Etiket rengi güncellenemedi.','color.default':'Varsayılan','color.mint':'Nane','color.sage':'Adaçayı','color.sand':'Kum','color.rose':'Gül','color.sky':'Gökyüzü','color.lavender':'Lavanta' },
  zh: {
    'color.default':'默认','color.mint':'薄荷绿','color.sage':'鼠尾草','color.sand':'沙色','color.rose':'玫瑰色','color.sky':'天空蓝','color.lavender':'薰衣草紫',
    'sort.title':'排序笔记','sort.manual':'自定义顺序','sort.updated-desc':'最近更新','sort.updated-asc':'最早更新','sort.created-desc':'最新创建','sort.created-asc':'最早创建','sort.title-asc':'标题 A–Z',
    'filter.title':'筛选笔记','filter.active':'已启用 {count} 个筛选条件','filter.hint':'缩小结果范围','filter.color':'颜色','filter.label':'标签','filter.allLabels':'所有标签','filter.updated':'更新时间','filter.anyTime':'任何时间','filter.today':'最近 24 小时','filter.week':'最近 7 天','filter.month':'最近 30 天','filter.reminder':'提醒','filter.all':'全部','filter.withReminder':'有提醒','filter.withoutReminder':'无提醒','filter.clear':'清除所有筛选条件',
    'settings.profile':'个人资料','settings.users':'用户','settings.data':'数据和备份','settings.labels':'标签','settings.signOut':'退出登录','about.version':'版本','about.source':'源代码','about.license':'许可证','about.storage':'存储','about.storageValue':'您的服务器 · SQLite',
  },
  hi: {
    'color.default':'डिफ़ॉल्ट','color.mint':'मिंट','color.sage':'सेज','color.sand':'रेत','color.rose':'गुलाबी','color.sky':'आसमानी','color.lavender':'लैवेंडर',
    'sort.title':'नोट क्रमबद्ध करें','sort.manual':'मनचाहा क्रम','sort.updated-desc':'हाल में अपडेट','sort.updated-asc':'सबसे पहले अपडेट','sort.created-desc':'नवीनतम बनाए गए','sort.created-asc':'सबसे पुराने बनाए गए','sort.title-asc':'शीर्षक A–Z',
    'filter.title':'नोट फ़िल्टर करें','filter.active':'{count} फ़िल्टर सक्रिय','filter.hint':'परिणाम सीमित करें','filter.color':'रंग','filter.label':'लेबल','filter.allLabels':'सभी लेबल','filter.updated':'अपडेट समय','filter.anyTime':'कभी भी','filter.today':'पिछले 24 घंटे','filter.week':'पिछले 7 दिन','filter.month':'पिछले 30 दिन','filter.reminder':'रिमाइंडर','filter.all':'सभी','filter.withReminder':'रिमाइंडर सहित','filter.withoutReminder':'रिमाइंडर बिना','filter.clear':'सभी फ़िल्टर हटाएँ',
    'settings.profile':'प्रोफ़ाइल','settings.users':'उपयोगकर्ता','settings.data':'डेटा और बैकअप','settings.labels':'लेबल','settings.signOut':'साइन आउट','about.version':'संस्करण','about.source':'स्रोत कोड','about.license':'लाइसेंस','about.storage':'स्टोरेज','about.storageValue':'आपका सर्वर · SQLite',
  },
  es: {
    'color.default':'Predeterminado','color.mint':'Menta','color.sage':'Salvia','color.sand':'Arena','color.rose':'Rosa','color.sky':'Cielo','color.lavender':'Lavanda',
    'sort.title':'Ordenar notas','sort.manual':'Orden personalizado','sort.updated-desc':'Actualizadas recientemente','sort.updated-asc':'Actualizadas primero','sort.created-desc':'Más recientes','sort.created-asc':'Más antiguas','sort.title-asc':'Título A–Z',
    'filter.title':'Filtrar notas','filter.active':'{count} filtros activos','filter.hint':'Acotar los resultados','filter.color':'Color','filter.label':'Etiqueta','filter.allLabels':'Todas las etiquetas','filter.updated':'Actualización','filter.anyTime':'Cualquier fecha','filter.today':'Últimas 24 horas','filter.week':'Últimos 7 días','filter.month':'Últimos 30 días','filter.reminder':'Recordatorio','filter.all':'Todos','filter.withReminder':'Con recordatorio','filter.withoutReminder':'Sin recordatorio','filter.clear':'Borrar todos los filtros',
    'settings.profile':'Perfil','settings.users':'Usuarios','settings.data':'Datos y copia','settings.labels':'Etiquetas','settings.signOut':'Cerrar sesión','about.version':'Versión','about.source':'Código fuente','about.license':'Licencia','about.storage':'Almacenamiento','about.storageValue':'Tu servidor · SQLite',
  },
  ar: {
    'color.default':'افتراضي','color.mint':'نعناعي','color.sage':'مريمي','color.sand':'رملي','color.rose':'وردي','color.sky':'سماوي','color.lavender':'لافندر',
    'sort.title':'ترتيب الملاحظات','sort.manual':'ترتيب مخصص','sort.updated-desc':'المحدّثة مؤخرًا','sort.updated-asc':'الأقدم تحديثًا','sort.created-desc':'الأحدث إنشاءً','sort.created-asc':'الأقدم إنشاءً','sort.title-asc':'العنوان A–Z',
    'filter.title':'تصفية الملاحظات','filter.active':'{count} عوامل تصفية نشطة','filter.hint':'تضييق النتائج','filter.color':'اللون','filter.label':'التصنيف','filter.allLabels':'كل التصنيفات','filter.updated':'تاريخ التحديث','filter.anyTime':'أي وقت','filter.today':'آخر 24 ساعة','filter.week':'آخر 7 أيام','filter.month':'آخر 30 يومًا','filter.reminder':'التذكير','filter.all':'الكل','filter.withReminder':'مع تذكير','filter.withoutReminder':'بدون تذكير','filter.clear':'مسح كل عوامل التصفية',
    'settings.profile':'الملف الشخصي','settings.users':'المستخدمون','settings.data':'البيانات والنسخ الاحتياطي','settings.labels':'التصنيفات','settings.signOut':'تسجيل الخروج','about.version':'الإصدار','about.source':'الشيفرة المصدرية','about.license':'الترخيص','about.storage':'التخزين','about.storageValue':'خادمك · SQLite',
  },
  fr: {
    'color.default':'Par défaut','color.mint':'Menthe','color.sage':'Sauge','color.sand':'Sable','color.rose':'Rose','color.sky':'Ciel','color.lavender':'Lavande',
    'sort.title':'Trier les notes','sort.manual':'Ordre personnalisé','sort.updated-desc':'Modifiées récemment','sort.updated-asc':'Modifiées en premier','sort.created-desc':'Créées récemment','sort.created-asc':'Créées en premier','sort.title-asc':'Titre A–Z',
    'filter.title':'Filtrer les notes','filter.active':'{count} filtres actifs','filter.hint':'Affiner les résultats','filter.color':'Couleur','filter.label':'Libellé','filter.allLabels':'Tous les libellés','filter.updated':'Mise à jour','filter.anyTime':'Toute période','filter.today':'Dernières 24 heures','filter.week':'7 derniers jours','filter.month':'30 derniers jours','filter.reminder':'Rappel','filter.all':'Tous','filter.withReminder':'Avec rappel','filter.withoutReminder':'Sans rappel','filter.clear':'Effacer tous les filtres',
    'settings.profile':'Profil','settings.users':'Utilisateurs','settings.data':'Données et sauvegarde','settings.labels':'Libellés','settings.signOut':'Se déconnecter','about.version':'Version','about.source':'Code source','about.license':'Licence','about.storage':'Stockage','about.storageValue':'Votre serveur · SQLite',
  },
  bn: {
    'color.default':'ডিফল্ট','color.mint':'মিন্ট','color.sage':'সেজ','color.sand':'বালি','color.rose':'গোলাপি','color.sky':'আকাশি','color.lavender':'ল্যাভেন্ডার',
    'sort.title':'নোট সাজান','sort.manual':'নিজস্ব ক্রম','sort.updated-desc':'সর্বশেষ আপডেট','sort.updated-asc':'আগে আপডেট করা','sort.created-desc':'সর্বশেষ তৈরি','sort.created-asc':'আগে তৈরি','sort.title-asc':'শিরোনাম A–Z',
    'filter.title':'নোট ফিল্টার করুন','filter.active':'{count}টি ফিল্টার সক্রিয়','filter.hint':'ফলাফল সীমিত করুন','filter.color':'রং','filter.label':'লেবেল','filter.allLabels':'সব লেবেল','filter.updated':'আপডেটের সময়','filter.anyTime':'যেকোনো সময়','filter.today':'গত ২৪ ঘণ্টা','filter.week':'গত ৭ দিন','filter.month':'গত ৩০ দিন','filter.reminder':'রিমাইন্ডার','filter.all':'সব','filter.withReminder':'রিমাইন্ডারসহ','filter.withoutReminder':'রিমাইন্ডার ছাড়া','filter.clear':'সব ফিল্টার মুছুন',
    'settings.profile':'প্রোফাইল','settings.users':'ব্যবহারকারী','settings.data':'ডেটা ও ব্যাকআপ','settings.labels':'লেবেল','settings.signOut':'সাইন আউট','about.version':'সংস্করণ','about.source':'সোর্স কোড','about.license':'লাইসেন্স','about.storage':'স্টোরেজ','about.storageValue':'আপনার সার্ভার · SQLite',
  },
  pt: {
    'color.default':'Padrão','color.mint':'Menta','color.sage':'Sálvia','color.sand':'Areia','color.rose':'Rosa','color.sky':'Céu','color.lavender':'Lavanda',
    'sort.title':'Ordenar notas','sort.manual':'Ordem personalizada','sort.updated-desc':'Atualizadas recentemente','sort.updated-asc':'Atualizadas primeiro','sort.created-desc':'Criadas recentemente','sort.created-asc':'Criadas primeiro','sort.title-asc':'Título A–Z',
    'filter.title':'Filtrar notas','filter.active':'{count} filtros ativos','filter.hint':'Restringir resultados','filter.color':'Cor','filter.label':'Marcador','filter.allLabels':'Todos os marcadores','filter.updated':'Atualização','filter.anyTime':'Qualquer data','filter.today':'Últimas 24 horas','filter.week':'Últimos 7 dias','filter.month':'Últimos 30 dias','filter.reminder':'Lembrete','filter.all':'Todos','filter.withReminder':'Com lembrete','filter.withoutReminder':'Sem lembrete','filter.clear':'Limpar todos os filtros',
    'settings.profile':'Perfil','settings.users':'Usuários','settings.data':'Dados e backup','settings.labels':'Marcadores','settings.signOut':'Sair','about.version':'Versão','about.source':'Código-fonte','about.license':'Licença','about.storage':'Armazenamento','about.storageValue':'Seu servidor · SQLite',
  },
  ru: {
    'color.default':'По умолчанию','color.mint':'Мятный','color.sage':'Шалфейный','color.sand':'Песочный','color.rose':'Розовый','color.sky':'Небесный','color.lavender':'Лавандовый',
    'sort.title':'Сортировать заметки','sort.manual':'Свой порядок','sort.updated-desc':'Недавно изменённые','sort.updated-asc':'Давно изменённые','sort.created-desc':'Недавно созданные','sort.created-asc':'Давно созданные','sort.title-asc':'Название А–Я',
    'filter.title':'Фильтровать заметки','filter.active':'Активных фильтров: {count}','filter.hint':'Уточнить результаты','filter.color':'Цвет','filter.label':'Ярлык','filter.allLabels':'Все ярлыки','filter.updated':'Дата изменения','filter.anyTime':'За всё время','filter.today':'Последние 24 часа','filter.week':'Последние 7 дней','filter.month':'Последние 30 дней','filter.reminder':'Напоминание','filter.all':'Все','filter.withReminder':'С напоминанием','filter.withoutReminder':'Без напоминания','filter.clear':'Сбросить все фильтры',
    'settings.profile':'Профиль','settings.users':'Пользователи','settings.data':'Данные и резервные копии','settings.labels':'Ярлыки','settings.signOut':'Выйти','about.version':'Версия','about.source':'Исходный код','about.license':'Лицензия','about.storage':'Хранилище','about.storageValue':'Ваш сервер · SQLite',
  },
};

export function normalizeLocale(value?: string | null): Locale {
  const short = value?.toLowerCase().split(/[-_]/)[0] as Locale | undefined;
  return short && languages.some((language) => language.value === short) ? short : 'en';
}

export function translate(locale: Locale, key: MessageKey, values?: Record<string, string | number>) {
  let message = featureTranslations[locale][key] || localeOverrides[locale][key] || translations[locale][key] || en[key];
  for (const [name, value] of Object.entries(values || {})) message = message.replaceAll(`{${name}}`, String(value));
  return message;
}

export function missingTranslationKeys(locale: Locale) {
  if (locale === 'en') return [] as MessageKey[];
  const localized = { ...translations[locale], ...localeOverrides[locale], ...featureTranslations[locale] };
  return (Object.keys(en) as MessageKey[]).filter((key) => !Object.prototype.hasOwnProperty.call(localized, key));
}

export function languageDirection(locale: Locale) {
  return languages.find((language) => language.value === locale)?.dir || 'ltr';
}
